### ISSUE TITLE
Virus??  VHO:Backdoor.Win32.Connvagent.gen

### ISSUE THREAD

**Issue by dvgamerr** [Bowarc/Lumin#8]
![image](https://github.com/Bowarc/Lumin/assets/10203425/34a25ca2-fb93-4628-88fb-90f420c4c96d)

**Comment by Bowarc** [comment]
Did you get it from the Release or you compiled it ?

**Comment by Bowarc** [comment]
It's obviously a false positive, but I'm curious what triggers it

**Comment by Bowarc** [comment]
Ok i found the problem, in the newer version (not yet in releases) i don't use a deamon but a small program to get the background window handle, and the method to get that is flagged by some AV.

I'll make a new release when i get the time tonight

**Comment by Bowarc** [comment]
Done, you can find the new version [here](https://github.com/Bowarc/Lumin/releases/tag/0.1.4), worker fetcher now is the only thing triggering AVs, but you can easily see the source code and / or compile it yourself
